//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cicaudittrail.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cicaudittrail.Resources.Properties", typeof(Properties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi.
        /// </summary>
        public static string CicFollowedPropertiesValues_CicRequestResultsFollowed {
            get {
                return ResourceManager.GetString("CicFollowedPropertiesValues_CicRequestResultsFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé le.
        /// </summary>
        public static string CicFollowedPropertiesValues_DateCreated {
            get {
                return ResourceManager.GetString("CicFollowedPropertiesValues_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pièces jointes.
        /// </summary>
        public static string CicMessageMail_CicMessageMailDocuments {
            get {
                return ResourceManager.GetString("CicMessageMail_CicMessageMailDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modéle de message envoyé.
        /// </summary>
        public static string CicMessageMail_CicMessageTemplate {
            get {
                return ResourceManager.GetString("CicMessageMail_CicMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi.
        /// </summary>
        public static string CicMessageMail_CicRequestResultsFollowed {
            get {
                return ResourceManager.GetString("CicMessageMail_CicRequestResultsFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date message.
        /// </summary>
        public static string CicMessageMail_DateMessage {
            get {
                return ResourceManager.GetString("CicMessageMail_DateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message reçu le.
        /// </summary>
        public static string CicMessageMail_DateMessageReceived {
            get {
                return ResourceManager.GetString("CicMessageMail_DateMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message envoyé le.
        /// </summary>
        public static string CicMessageMail_DateMessageSent {
            get {
                return ResourceManager.GetString("CicMessageMail_DateMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier.
        /// </summary>
        public static string CicMessageMail_Document {
            get {
                return ResourceManager.GetString("CicMessageMail_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message envoyé ?.
        /// </summary>
        public static string CicMessageMail_IsSent {
            get {
                return ResourceManager.GetString("CicMessageMail_IsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string CicMessageMail_MessageContent {
            get {
                return ResourceManager.GetString("CicMessageMail_MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message reçu.
        /// </summary>
        public static string CicMessageMail_MessageReceived {
            get {
                return ResourceManager.GetString("CicMessageMail_MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message envoyé.
        /// </summary>
        public static string CicMessageMail_MessageSent {
            get {
                return ResourceManager.GetString("CicMessageMail_MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet.
        /// </summary>
        public static string CicMessageMail_ObjetMessage {
            get {
                return ResourceManager.GetString("CicMessageMail_ObjetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sens.
        /// </summary>
        public static string CicMessageMail_Sens {
            get {
                return ResourceManager.GetString("CicMessageMail_Sens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur.
        /// </summary>
        public static string CicMessageMail_UserMessage {
            get {
                return ResourceManager.GetString("CicMessageMail_UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message envoyé par.
        /// </summary>
        public static string CicMessageMail_UserMessageSent {
            get {
                return ResourceManager.GetString("CicMessageMail_UserMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse de.
        /// </summary>
        public static string CicMessageMail_UserResponseSent {
            get {
                return ResourceManager.GetString("CicMessageMail_UserResponseSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail.
        /// </summary>
        public static string CicMessageMailDocuments_CicMessageMail {
            get {
                return ResourceManager.GetString("CicMessageMailDocuments_CicMessageMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date création.
        /// </summary>
        public static string CicMessageMailDocuments_DateCreated {
            get {
                return ResourceManager.GetString("CicMessageMailDocuments_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pièce jointe.
        /// </summary>
        public static string CicMessageMailDocuments_DocumentName {
            get {
                return ResourceManager.GetString("CicMessageMailDocuments_DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        public static string CicMessageMailDocuments_DocumentType {
            get {
                return ResourceManager.GetString("CicMessageMailDocuments_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        public static string CicMessageTemplateCode {
            get {
                return ResourceManager.GetString("CicMessageTemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le code.
        /// </summary>
        public static string CicMessageTemplateCodeRequired {
            get {
                return ResourceManager.GetString("CicMessageTemplateCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu mail.
        /// </summary>
        public static string CicMessageTemplateContenuMail {
            get {
                return ResourceManager.GetString("CicMessageTemplateContenuMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le contenu du mail.
        /// </summary>
        public static string CicMessageTemplateContenuMailRequired {
            get {
                return ResourceManager.GetString("CicMessageTemplateContenuMailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création modèle de message.
        /// </summary>
        public static string CicMessageTemplateCreateTitle {
            get {
                return ResourceManager.GetString("CicMessageTemplateCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé le.
        /// </summary>
        public static string CicMessageTemplateDateCreated {
            get {
                return ResourceManager.GetString("CicMessageTemplateDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intitulé.
        /// </summary>
        public static string CicMessageTemplateLibelle {
            get {
                return ResourceManager.GetString("CicMessageTemplateLibelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir l&apos;intitulé .
        /// </summary>
        public static string CicMessageTemplateLibelleRequired {
            get {
                return ResourceManager.GetString("CicMessageTemplateLibelleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet mail.
        /// </summary>
        public static string CicMessageTemplateObjetMail {
            get {
                return ResourceManager.GetString("CicMessageTemplateObjetMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir l&apos;objet du mail.
        /// </summary>
        public static string CicMessageTemplateObjetMailRequired {
            get {
                return ResourceManager.GetString("CicMessageTemplateObjetMailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé par.
        /// </summary>
        public static string CicMessageTemplateUserCreated {
            get {
                return ResourceManager.GetString("CicMessageTemplateUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requête.
        /// </summary>
        public static string CicRequest {
            get {
                return ResourceManager.GetString("CicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modéle de message envoyé.
        /// </summary>
        public static string CicRequest_CicMessageTemplate {
            get {
                return ResourceManager.GetString("CicRequest_CicMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétés.
        /// </summary>
        public static string CicRequest_Properties {
            get {
                return ResourceManager.GetString("CicRequest_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        public static string CicRequestCode {
            get {
                return ResourceManager.GetString("CicRequestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le code.
        /// </summary>
        public static string CicRequestCodeRequired {
            get {
                return ResourceManager.GetString("CicRequestCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date création.
        /// </summary>
        public static string CicRequestDateCreated {
            get {
                return ResourceManager.GetString("CicRequestDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date modification.
        /// </summary>
        public static string CicRequestDateUpdated {
            get {
                return ResourceManager.GetString("CicRequestDateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string CicRequestExecution_Action {
            get {
                return ResourceManager.GetString("CicRequestExecution_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message envoyé.
        /// </summary>
        public static string CicRequestExecution_CicMessageMail {
            get {
                return ResourceManager.GetString("CicRequestExecution_CicMessageMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat Centif tiré.
        /// </summary>
        public static string CicRequestExecution_CT {
            get {
                return ResourceManager.GetString("CicRequestExecution_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression.
        /// </summary>
        public static string CicRequestExecution_D {
            get {
                return ResourceManager.GetString("CicRequestExecution_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string CicRequestExecution_DateAction {
            get {
                return ResourceManager.GetString("CicRequestExecution_DateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution.
        /// </summary>
        public static string CicRequestExecution_E {
            get {
                return ResourceManager.GetString("CicRequestExecution_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi.
        /// </summary>
        public static string CicRequestExecution_F {
            get {
                return ResourceManager.GetString("CicRequestExecution_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi annulé.
        /// </summary>
        public static string CicRequestExecution_FA {
            get {
                return ResourceManager.GetString("CicRequestExecution_FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi confirmé.
        /// </summary>
        public static string CicRequestExecution_FC {
            get {
                return ResourceManager.GetString("CicRequestExecution_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Justificatifs demandés.
        /// </summary>
        public static string CicRequestExecution_MS {
            get {
                return ResourceManager.GetString("CicRequestExecution_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification.
        /// </summary>
        public static string CicRequestExecution_U {
            get {
                return ResourceManager.GetString("CicRequestExecution_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        public static string CicRequestExecution_UserAction {
            get {
                return ResourceManager.GetString("CicRequestExecution_UserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requête.
        /// </summary>
        public static string CicRequestExecutionCicRequest {
            get {
                return ResourceManager.GetString("CicRequestExecutionCicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requête.
        /// </summary>
        public static string CicRequestExecutionCicRequestId {
            get {
                return ResourceManager.GetString("CicRequestExecutionCicRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element suivi.
        /// </summary>
        public static string CicRequestExecutionCicRequestResultsFollowed {
            get {
                return ResourceManager.GetString("CicRequestExecutionCicRequestResultsFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element suivi.
        /// </summary>
        public static string CicRequestExecutionCicRequestResultsFollowedId {
            get {
                return ResourceManager.GetString("CicRequestExecutionCicRequestResultsFollowedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date suppression.
        /// </summary>
        public static string CicRequestExecutionDateDeleted {
            get {
                return ResourceManager.GetString("CicRequestExecutionDateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécutée le.
        /// </summary>
        public static string CicRequestExecutionDateExecuted {
            get {
                return ResourceManager.GetString("CicRequestExecutionDateExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date suivi.
        /// </summary>
        public static string CicRequestExecutionDateFollowed {
            get {
                return ResourceManager.GetString("CicRequestExecutionDateFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifiée le.
        /// </summary>
        public static string CicRequestExecutionDateUpdated {
            get {
                return ResourceManager.GetString("CicRequestExecutionDateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimée par.
        /// </summary>
        public static string CicRequestExecutionUserDeleted {
            get {
                return ResourceManager.GetString("CicRequestExecutionUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécutée par.
        /// </summary>
        public static string CicRequestExecutionUserExecuted {
            get {
                return ResourceManager.GetString("CicRequestExecutionUserExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivie par.
        /// </summary>
        public static string CicRequestExecutionUserFollowed {
            get {
                return ResourceManager.GetString("CicRequestExecutionUserFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifée par.
        /// </summary>
        public static string CicRequestExecutionUserUpdated {
            get {
                return ResourceManager.GetString("CicRequestExecutionUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intitulé.
        /// </summary>
        public static string CicRequestLibelle {
            get {
                return ResourceManager.GetString("CicRequestLibelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le libellé.
        /// </summary>
        public static string CicRequestLibelleRequired {
            get {
                return ResourceManager.GetString("CicRequestLibelleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requête.
        /// </summary>
        public static string CicRequestRequest {
            get {
                return ResourceManager.GetString("CicRequestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir la requête à exécuter.
        /// </summary>
        public static string CicRequestRequestRequired {
            get {
                return ResourceManager.GetString("CicRequestRequestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulé.
        /// </summary>
        public static string CicRequestResultsFollowed_A {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowed_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat Centif tiré.
        /// </summary>
        public static string CicRequestResultsFollowed_C {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowed_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mails échangés.
        /// </summary>
        public static string CicRequestResultsFollowed_CicMessageMails {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowed_CicMessageMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En attente.
        /// </summary>
        public static string CicRequestResultsFollowed_E {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowed_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Justificatifs demandés.
        /// </summary>
        public static string CicRequestResultsFollowed_ME {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowed_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Justificatifs reçus.
        /// </summary>
        public static string CicRequestResultsFollowed_MR {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowed_MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suspect.
        /// </summary>
        public static string CicRequestResultsFollowed_S {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowed_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requête concernée.
        /// </summary>
        public static string CicRequestResultsFollowedCicRequest {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedCicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires.
        /// </summary>
        public static string CicRequestResultsFollowedComments {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effectué le.
        /// </summary>
        public static string CicRequestResultsFollowedDateCreated {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu.
        /// </summary>
        public static string CicRequestResultsFollowedRowCCicRequestResultsFollowedRowContent {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedRowCCicRequestResultsFollowedRowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu.
        /// </summary>
        public static string CicRequestResultsFollowedRowContent {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedRowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche de suivis effectués.
        /// </summary>
        public static string CicRequestResultsFollowedSearchTitle {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        public static string CicRequestResultsFollowedStatut {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedStatut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effectué par.
        /// </summary>
        public static string CicRequestResultsFollowedUserCreated {
            get {
                return ResourceManager.GetString("CicRequestResultsFollowedUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé par.
        /// </summary>
        public static string CicRequestUserCreated {
            get {
                return ResourceManager.GetString("CicRequestUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié par.
        /// </summary>
        public static string CicRequestUserUpdated {
            get {
                return ResourceManager.GetString("CicRequestUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création rôle.
        /// </summary>
        public static string CicRole_create {
            get {
                return ResourceManager.GetString("CicRole_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date création.
        /// </summary>
        public static string CicRole_DateCreated {
            get {
                return ResourceManager.GetString("CicRole_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié le.
        /// </summary>
        public static string CicRole_DateUpdated {
            get {
                return ResourceManager.GetString("CicRole_DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification rôle.
        /// </summary>
        public static string CicRole_edit {
            get {
                return ResourceManager.GetString("CicRole_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste rôles.
        /// </summary>
        public static string CicRole_list {
            get {
                return ResourceManager.GetString("CicRole_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé par.
        /// </summary>
        public static string CicRole_UserCreated {
            get {
                return ResourceManager.GetString("CicRole_UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié par.
        /// </summary>
        public static string CicRole_UserUpdated {
            get {
                return ResourceManager.GetString("CicRole_UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir un role.
        /// </summary>
        public static string CicUserRole_CicRoleId_Required {
            get {
                return ResourceManager.GetString("CicUserRole_CicRoleId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création attribution de rôle.
        /// </summary>
        public static string CicUserRole_create {
            get {
                return ResourceManager.GetString("CicUserRole_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date création.
        /// </summary>
        public static string CicUserRole_DateCreated {
            get {
                return ResourceManager.GetString("CicUserRole_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié le.
        /// </summary>
        public static string CicUserRole_DateUpdated {
            get {
                return ResourceManager.GetString("CicUserRole_DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification attribution de rôle.
        /// </summary>
        public static string CicUserRole_edit {
            get {
                return ResourceManager.GetString("CicUserRole_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role.
        /// </summary>
        public static string CicUserRole_Role {
            get {
                return ResourceManager.GetString("CicUserRole_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé par.
        /// </summary>
        public static string CicUserRole_UserCreated {
            get {
                return ResourceManager.GetString("CicUserRole_UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string CicUserRole_Username {
            get {
                return ResourceManager.GetString("CicUserRole_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un username.
        /// </summary>
        public static string CicUserRole_Username_Required {
            get {
                return ResourceManager.GetString("CicUserRole_Username_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié par.
        /// </summary>
        public static string CicUserRole_UserUpdated {
            get {
                return ResourceManager.GetString("CicUserRole_UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôle.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir l&apos;intitulé du rôle.
        /// </summary>
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matricule.
        /// </summary>
        public static string UserMatricule {
            get {
                return ResourceManager.GetString("UserMatricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le matricule de l&apos;agent.
        /// </summary>
        public static string UserMatriculeRequired {
            get {
                return ResourceManager.GetString("UserMatriculeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string UserNom {
            get {
                return ResourceManager.GetString("UserNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string UserPrenom {
            get {
                return ResourceManager.GetString("UserPrenom", resourceCulture);
            }
        }
    }
}
